//map function for trees
//return a new tree with updated values

/*
 * Basic tree that stores a value.
*/
var Tree = function (value) {
  this.value = value;
  this.children = [];
};

//return the same tree
Tree.prototype.mapInPlace = function(callback) {
  this.value = new Tree(callback(this.value));

  newTree.children = this.children.map(function(child) {
    return child.mapInPlace(callback);
  });

}

//functional approach
Tree.prototype.map = function(callback) {
  var newTree = callback(this.value);

  this.children.forEach(function(child) {
    return child.mapInPlace(callback);
  });

  //void 0; <- wtf
  //very odd little thing
  //void is a unary operator
  //evaluates expression (0), that expression returns undefined
  //this whole thing evaluates to undefined
  //void 0; undefined;
  //no code here: you'll see it more commonly on event handlers
  //very obscure
}

Tree.prototype.map = function (callback) {
  // TODO: return a new tree with the same structure as `this`,
  //       with values generated by the callback
  var result = new Tree();

  var traverseTree = function(result, treeNode) {
    //current result node value gets updated value
    result.value = callback(treeNode.value)

    //does node have children?
    if (treeNode.children.length > 0) {
      //recurse through child nodes
      for (var i = 0; i < treeNode.children.length; i++) {
        //create a child and apply callback 
        var child = new Tree();
        result.addChild(child);
        traverseTree(child, treeNode.children[i]);

      }
    }

  }

  traverseTree(result, this);
  return result;
};

/**
 * You shouldn't need to change anything below here,
 * but feel free to read it.
 */

/**
  * add an immediate child
  * (wrap values in Tree nodes if they're not already)
  */
Tree.prototype.addChild = function (child) {
  if (! child ||  ! (child instanceof Tree)){
    child = new Tree(child);
  }

  if (! this.isDescendant(child)) {
    this.children.push(child);
  } else {
    throw new Error("That child is already a child of this tree");
  }
  // return the new child node for convenience
  return child;
};

/**
  * check to see if the provided tree is already a child of this
  * tree __or any of its sub trees__
  */
Tree.prototype.isDescendant = function (child) {
  if (this.children.indexOf(child) !== -1) {
    // `child` is an immediate child of this tree
    return true;
  } else {
    for (var i = 0; i < this.children.length; i++) {
      if(this.children[i].isDescendant(child)){
        // `child` is descendant of this tree
        return true;
      }
    }
    return false;
  }
};

/**
  * remove an immediate child
  */
Tree.prototype.removeChild = function (child) {
  var index = this.children.indexOf(child);
  if (index !== -1) {
    // remove the child
    this.children.splice(index,1);
  } else {
    throw new Error("That node is not an immediate child of this tree");
  }
};